### ISSUE TITLE
errors running role_update.sh

### ISSUE THREAD

**Issue by satyaakam** [RestComm/netflix-oss-tracker-infra#4]
bash role_update.sh 
Removing current roles in '/home/satyaakam/netflix-oss-tracker-infra/ansible/roles/external/*'
- extracting angstwad.docker_ubuntu to /home/satyaakam/netflix-oss-tracker-infra/ansible/roles/external/angstwad.docker_ubuntu
- angstwad.docker_ubuntu was installed successfully
- extracting Bessonov.docker-compose to /home/satyaakam/netflix-oss-tracker-infra/ansible/roles/external/Bessonov.docker-compose
- Bessonov.docker-compose was installed successfully
- downloading role 'locales', owned by tersmitten
 [WARNING]: - tersmitten.locales was NOT installed successfully: - sorry, tersmitten.locales was not found on https://galaxy.ansible.com.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Update failed. Please don't commit or push roles till you fix the issue
Exiting...

**Comment by mcred** [comment]
I ran into the same issues recently. I was able to fix it with the changes in Pull Request #3.

**Comment by gsaslis** [comment]
ah - thanks for that @mcred!

**Comment by deruelle** [comment]
Pull Request #3 merged. closing. Thanks @mcred  for the contribution and @gsaslis  for the review !
